// react/bind/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {

  constructor() {
    super();
    this.state = {
      oneWayBinding: 'This is a one way Binding',
      twoWayBinding: ''
    }
  }

  updateBinding = (e) => {
    let twoWayBinding = e.target.value;
    this.setState(oldState => ({
      ...oldState,
      twoWayBinding
    }))
  }

  render() {
    let { oneWayBinding, twoWayBinding } = this.state;
    return (
      <div className="App flex-container flex-horizontal-center">
        <div>
          <img src={logo} className="App-logo" alt="logo" />
          <div className="flex-container flex-center">
            <div className="loc-logo"></div>
          </div>
          <h1>One and Two Way Binding in React</h1>
          <div className="flex-container flex-column flex-horizontal-start">
            <div className="flex-container flex-vertical-center">
              <h3 className="one-way">One Way Binding: </h3>
              <div>{oneWayBinding}</div>
            </div>
            <div className="flex-container flex-veritcal-center">
              <h3>Two Way Binding: </h3>
              <div className="flex-container flex-vertical-center">
                <input className="twoBind" value={twoWayBinding} onChange={(e) => this.updateBinding(e)} />
              </div>
            </div>
            <div className="flex-container">
              <div className="react-results">React results: </div>
              <div>{twoWayBinding}</div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default App;

// angular/bind/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'bind';

  onewaybind = 'this is my one way bind';

  inputValue = "";
}

<!--The content below is only a placeholder and can be replaced.-->
<div class="flex-container flex-column flex-center">
  <img width="300" alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
  <div class="loc-logo"></div>
</div>
<h2>Here are some links to help you start: </h2>
<div class="flex-container flex-column">
  <div class="flex-container flex-vertical-center">
    <h3 class='onewaybinding'>One Way Binding:</h3>
    <div [innerHTML]="onewaybind"></div>
    <div>{{onewaybind}}</div>
  </div>
  <div class="flex-container">
    <h3>Two Way Binding:</h3>
    <div class="flex-container flex-vertical-center">
      <input [(ngModel)]="inputValue" />
      <div><strong>Result: </strong>{{inputValue}}</div>
    </div>
  </div>
</div>
